import mongoose from "mongoose"

const artworksData = [
    {
        "Region": "Śląsk",
        "Sygnatura nagrania": "SKML-010",
        "Incipit": "Incipit-50",
        "Numer wątku muzycznego": 71,
        "Numer w publikacji": 227,
        "Miejscowość": "Tarnowskie Góry",
        "Sposób wykonania": "Gitara elektryczna",
        "Funkcja utworu": "Nowoczesna",
        "Link do nagrania": "https://example.com/recording/010",
        "Źródło": "Nagranie studyjne",
        "Klasyfikacja melodyczna": "Skala heksatoniczna",
        "Kategoria": "Śląska Kolekcja Muzyki Ludowej",
        "Wykorzystanie w publikacji": "W książce muzycznej",
        "Struktura tekstu": "Refrenowa",
        "Uwagi": "Współczesne brzmienie",
        "Obecność w źródłach": "Nagranie festiwalowe",
        "Tytuł": "Nowoczesne Brzmienia Tarnowskich Gór",
        "Artyści": [
            "Piotr Szymański",
        ],
        "Rok": 2020,
    },
    {
        "Region": "Śląsk",
        "Sygnatura nagrania": "SKML-909",
        "Incipit": "Incipit-49",
        "Numer wątku muzycznego": 69,
        "Numer w publikacji": 215,
        "Miejscowość": "Zabrze",
        "Sposób wykonania": "Saksofon",
        "Funkcja utworu": "Folklorystyczna",
        "Link do nagrania": "https://example.com/recording/909",
        "Źródło": "Zbiór ludowy",
        "Klasyfikacja melodyczna": "Skala lidyjska",
        "Kategoria": "Śląska Kolekcja Muzyki Ludowej",
        "Wykorzystanie w publikacji": "W dokumentacji muzycznej",
        "Struktura tekstu": "Kupletowa",
        "Uwagi": "Nowoczesne interpretacje",
        "Obecność w źródłach": "Nagranie koncertowe",
        "Tytuł": "Saksofonowe Dźwięki Zabrza",
        "Artyści": [
            "Aleksandra Wiśniewska",
        ],
        "Rok": 2018,
    },
    {
        "Region": "Śląsk",
        "Sygnatura nagrania": "SKML-808",
        "Incipit": "Incipit-48",
        "Numer wątku muzycznego": 67,
        "Numer w publikacji": 203,
        "Miejscowość": "Opole",
        "Sposób wykonania": "Basy",
        "Funkcja utworu": "Świąteczna",
        "Link do nagrania": "https://example.com/recording/808",
        "Źródło": "Tradycja świąteczna",
        "Klasyfikacja melodyczna": "Skala mixolydzka",
        "Kategoria": "Śląska Kolekcja Muzyki Ludowej",
        "Wykorzystanie w publikacji": "W antologii regionalnej",
        "Struktura tekstu": "Narracyjna",
        "Uwagi": "Folklor świąteczny",
        "Obecność w źródłach": "Nagranie archiwalne",
        "Tytuł": "Świąteczne Nuty z Opola",
        "Artyści": [
            "Tomasz Baranowski",
        ],
        "Rok": 2015,
    },
    {
        "Region": "Śląsk",
        "Sygnatura nagrania": "SKML-707",
        "Incipit": "Incipit-47",
        "Numer wątku muzycznego": 65,
        "Numer w publikacji": 192,
        "Miejscowość": "Bielsko-Biała",
        "Sposób wykonania": "Flet",
        "Funkcja utworu": "Romantyczna",
        "Link do nagrania": "https://example.com/recording/707",
        "Źródło": "Kolekcja prywatna",
        "Klasyfikacja melodyczna": "Skala frygijska",
        "Kategoria": "Śląska Kolekcja Muzyki Ludowej",
        "Wykorzystanie w publikacji": "W książce etnograficznej",
        "Struktura tekstu": "Liryczna",
        "Uwagi": "Zachowanie dawnych melodii",
        "Obecność w źródłach": "Rejestracja terenowa",
        "Tytuł": "Fletowe Melodie Bielska-Białej",
        "Artyści": [
            "Maria Kowalska",
        ],
        "Rok": 2013,
    },
    {
        "Region": "Śląsk",
        "Sygnatura nagrania": "SKML-606",
        "Incipit": "Incipit-46",
        "Numer wątku muzycznego": 63,
        "Numer w publikacji": 181,
        "Miejscowość": "Rybnik",
        "Sposób wykonania": "Harmonijka ustna",
        "Funkcja utworu": "Biesiadna",
        "Link do nagrania": "https://example.com/recording/606",
        "Źródło": "Tradycja rodzinna",
        "Klasyfikacja melodyczna": "Skala bluesowa",
        "Kategoria": "Śląska Kolekcja Muzyki Ludowej",
        "Wykorzystanie w publikacji": "W albumie muzycznym",
        "Struktura tekstu": "Powtarzalna",
        "Uwagi": "Popularność w lokalnej społeczności",
        "Obecność w źródłach": "Nagranie festiwalowe",
        "Tytuł": "Harmonijkowe Dźwięki Rybnika",
        "Artyści": [
            "Piotr Nowak",
        ],
        "Rok": 2010,
    },
    {
        "Region": "Śląsk",
        "Sygnatura nagrania": "SKML-505",
        "Incipit": "Incipit-45",
        "Numer wątku muzycznego": 61,
        "Numer w publikacji": 174,
        "Miejscowość": "Zabrze",
        "Sposób wykonania": "Bas",
        "Funkcja utworu": "Folklorystyczna",
        "Link do nagrania": "https://example.com/recording/505",
        "Źródło": "Tradycja regionalna",
        "Klasyfikacja melodyczna": "Skala dorycka",
        "Kategoria": "Śląska Kolekcja Muzyki Ludowej",
        "Wykorzystanie w publikacji": "W dokumentacji muzycznej",
        "Struktura tekstu": "Narracyjna",
        "Uwagi": "Zachowanie lokalnego folkloru",
        "Obecność w źródłach": "Kolekcja prywatna",
        "Tytuł": "Basowe Brzmienia Zabrza",
        "Artyści": [
            "Tomasz Baranowski",
        ],
        "Rok": 2012,
    },
    {
        "Region": "Śląsk",
        "Sygnatura nagrania": "SKML-404",
        "Incipit": "Incipit-44",
        "Numer wątku muzycznego": 59,
        "Numer w publikacji": 156,
        "Miejscowość": "Gliwice",
        "Sposób wykonania": "Gitara",
        "Funkcja utworu": "Romantyczna",
        "Link do nagrania": "https://example.com/recording/404",
        "Źródło": "Nagranie prywatne",
        "Klasyfikacja melodyczna": "Skala mixolydzka",
        "Kategoria": "Śląska Kolekcja Muzyki Ludowej",
        "Wykorzystanie w publikacji": "W antologii regionalnej",
        "Struktura tekstu": "Liryczna",
        "Uwagi": "Fuzja nowoczesności z tradycją",
        "Obecność w źródłach": "Nagranie współczesne",
        "Tytuł": "Gitarowe Dźwięki Gliwic",
        "Artyści": [
            "Aleksandra Wiśniewska",
        ],
        "Rok": 2008,
    },
    {
        "Region": "Śląsk",
        "Sygnatura nagrania": "SKML-303",
        "Incipit": "Incipit-43",
        "Numer wątku muzycznego": 57,
        "Numer w publikacji": 138,
        "Miejscowość": "Sosnowiec",
        "Sposób wykonania": "Akordeon",
        "Funkcja utworu": "Świąteczna",
        "Link do nagrania": "https://example.com/recording/303",
        "Źródło": "Zbiór etnograficzny",
        "Klasyfikacja melodyczna": "Skala pentatoniczna",
        "Kategoria": "Śląska Kolekcja Muzyki Ludowej",
        "Wykorzystanie w publikacji": "W albumie muzycznym",
        "Struktura tekstu": "Refrenowa",
        "Uwagi": "Elementy kultury śląskiej",
        "Obecność w źródłach": "Nagranie dokumentacyjne",
        "Tytuł": "Akordeonowe Melodie Sosnowca",
        "Artyści": [
            "Piotr Szymański",
        ],
        "Rok": 2004,
    },
    {
        "Region": "Śląsk",
        "Sygnatura nagrania": "SKML-202",
        "Incipit": "Incipit-42",
        "Numer wątku muzycznego": 55,
        "Numer w publikacji": 120,
        "Miejscowość": "Częstochowa",
        "Sposób wykonania": "Skrzypce",
        "Funkcja utworu": "Obrzędowa",
        "Link do nagrania": "https://example.com/recording/202",
        "Źródło": "Dziedzictwo ludowe",
        "Klasyfikacja melodyczna": "Skala molowa",
        "Kategoria": "Śląska Kolekcja Muzyki Ludowej",
        "Wykorzystanie w publikacji": "W opracowaniu etnograficznym",
        "Struktura tekstu": "Narracyjna",
        "Uwagi": "Autentyczne wykonanie",
        "Obecność w źródłach": "Nagranie terenowe",
        "Tytuł": "Skrzypcowe Echo Częstochowy",
        "Artyści": [
            "Maria Kowalska",
        ],
        "Rok": 2000,
    },
    {
        "Region": "Śląsk",
        "Sygnatura nagrania": "SKML-101",
        "Incipit": "Incipit-41",
        "Numer wątku muzycznego": 53,
        "Numer w publikacji": 102,
        "Miejscowość": "Katowice",
        "Sposób wykonania": "Harmonia",
        "Funkcja utworu": "Taneczna",
        "Link do nagrania": "https://example.com/recording/101",
        "Źródło": "Tradycja regionalna",
        "Klasyfikacja melodyczna": "Skala durowa",
        "Kategoria": "Śląska Kolekcja Muzyki Ludowej",
        "Wykorzystanie w publikacji": "W zbiorze pieśni",
        "Struktura tekstu": "Kupletowa",
        "Uwagi": "Zachowanie lokalnych melodii",
        "Obecność w źródłach": "Nagranie archiwalne",
        "Tytuł": "Rytmy Katowic",
        "Artyści": [
            "Jan Nowak",
        ],
        "Rok": 1995,
    },
    {
        "Region": "Kaszuby",
        "Sygnatura nagrania": "KPL-010",
        "Incipit": "Incipit-40",
        "Numer wątku muzycznego": 51,
        "Numer w publikacji": 165,
        "Miejscowość": "Gdańsk",
        "Sposób wykonania": "Gitara elektryczna",
        "Funkcja utworu": "Nowoczesna",
        "Link do nagrania": "https://example.com/recording/010",
        "Źródło": "Nagranie studyjne",
        "Klasyfikacja melodyczna": "Skala bluesowa",
        "Kategoria": "Kaszubskie Pieśni Ludowe",
        "Wykorzystanie w publikacji": "W książce muzycznej",
        "Struktura tekstu": "Kupletowa",
        "Uwagi": "Innowacyjne interpretacje",
        "Obecność w źródłach": "Nagranie koncertowe",
        "Tytuł": "Nowe Brzmienia z Gdańska",
        "Artyści": [
            "Tomasz Baranowski",
        ],
        "Rok": 2020,
    },
    {
        "Region": "Kaszuby",
        "Sygnatura nagrania": "KPL-999",
        "Incipit": "Incipit-39",
        "Numer wątku muzycznego": 49,
        "Numer w publikacji": 152,
        "Miejscowość": "Słupsk",
        "Sposób wykonania": "Klarnet",
        "Funkcja utworu": "Liryczna",
        "Link do nagrania": "https://example.com/recording/999",
        "Źródło": "Kolekcja prywatna",
        "Klasyfikacja melodyczna": "Skala heksatoniczna",
        "Kategoria": "Kaszubskie Pieśni Ludowe",
        "Wykorzystanie w publikacji": "W opracowaniu etnograficznym",
        "Struktura tekstu": "Refrenowa",
        "Uwagi": "Fuzja tradycji z nowoczesnością",
        "Obecność w źródłach": "Nagranie współczesne",
        "Tytuł": "Klarnetowe Pieśni Słupska",
        "Artyści": [
            "Aleksandra Wiśniewska",
        ],
        "Rok": 2017,
    },
    {
        "Region": "Kaszuby",
        "Sygnatura nagrania": "KPL-888",
        "Incipit": "Incipit-38",
        "Numer wątku muzycznego": 47,
        "Numer w publikacji": 140,
        "Miejscowość": "Kartuzy",
        "Sposób wykonania": "Saksofon",
        "Funkcja utworu": "Romantyczna",
        "Link do nagrania": "https://example.com/recording/888",
        "Źródło": "Rejestracja terenowa",
        "Klasyfikacja melodyczna": "Skala frygijska",
        "Kategoria": "Kaszubskie Pieśni Ludowe",
        "Wykorzystanie w publikacji": "W monografii regionalnej",
        "Struktura tekstu": "Liryczna",
        "Uwagi": "Nowoczesne aranżacje",
        "Obecność w źródłach": "Nagranie festiwalowe",
        "Tytuł": "Saksofonowe Melodie z Kartuz",
        "Artyści": [
            "Piotr Szymański",
        ],
        "Rok": 2019,
    },
    {
        "Region": "Kaszuby",
        "Sygnatura nagrania": "KPL-777",
        "Incipit": "Incipit-37",
        "Numer wątku muzycznego": 45,
        "Numer w publikacji": 134,
        "Miejscowość": "Chojnice",
        "Sposób wykonania": "Basy",
        "Funkcja utworu": "Obrzędowa",
        "Link do nagrania": "https://example.com/recording/777",
        "Źródło": "Dziedzictwo kulturowe",
        "Klasyfikacja melodyczna": "Skala lidyjska",
        "Kategoria": "Kaszubskie Pieśni Ludowe",
        "Wykorzystanie w publikacji": "W dokumentacji folklorystycznej",
        "Struktura tekstu": "Narracyjna",
        "Uwagi": "Zachowanie dawnych tradycji",
        "Obecność w źródłach": "Archiwum regionalne",
        "Tytuł": "Basowe Dźwięki Chojnic",
        "Artyści": [
            "Anna Wiśniewska",
        ],
        "Rok": 2016,
    },
    {
        "Region": "Kaszuby",
        "Sygnatura nagrania": "KPL-666",
        "Incipit": "Incipit-36",
        "Numer wątku muzycznego": 43,
        "Numer w publikacji": 128,
        "Miejscowość": "Puck",
        "Sposób wykonania": "Harmonijka ustna",
        "Funkcja utworu": "Imprezowa",
        "Link do nagrania": "https://example.com/recording/666",
        "Źródło": "Tradycja oralna",
        "Klasyfikacja melodyczna": "Skala bluesowa",
        "Kategoria": "Kaszubskie Pieśni Ludowe",
        "Wykorzystanie w publikacji": "W zbiorze pieśni ludowych",
        "Struktura tekstu": "Humorystyczna",
        "Uwagi": "Elementy humorystyczne w muzyce",
        "Obecność w źródłach": "Nagranie współczesne",
        "Tytuł": "Wesołe Nuty z Pucka",
        "Artyści": [
            "Marek Nowak",
        ],
        "Rok": 2014,
    },
    {
        "Region": "Kaszuby",
        "Sygnatura nagrania": "KPL-555",
        "Incipit": "Incipit-35",
        "Numer wątku muzycznego": 41,
        "Numer w publikacji": 116,
        "Miejscowość": "Gdynia",
        "Sposób wykonania": "Gitara",
        "Funkcja utworu": "Liryczna",
        "Link do nagrania": "https://example.com/recording/555",
        "Źródło": "Nagranie terenowe",
        "Klasyfikacja melodyczna": "Skala mixolydzka",
        "Kategoria": "Kaszubskie Pieśni Ludowe",
        "Wykorzystanie w publikacji": "W antologii regionalnej",
        "Struktura tekstu": "Kupletowa",
        "Uwagi": "Współczesne aranżacje",
        "Obecność w źródłach": "Nagranie festiwalowe",
        "Tytuł": "Gitarowe Pieśni Gdyńskie",
        "Artyści": [
            "Tomasz Baranowski",
        ],
        "Rok": 2013,
    },
    {
        "Region": "Kaszuby",
        "Sygnatura nagrania": "KPL-444",
        "Incipit": "Incipit-34",
        "Numer wątku muzycznego": 39,
        "Numer w publikacji": 104,
        "Miejscowość": "Wejherowo",
        "Sposób wykonania": "Flet",
        "Funkcja utworu": "Religijna",
        "Link do nagrania": "https://example.com/recording/444",
        "Źródło": "Zbiór kościelny",
        "Klasyfikacja melodyczna": "Skala pentatoniczna",
        "Kategoria": "Kaszubskie Pieśni Ludowe",
        "Wykorzystanie w publikacji": "W opracowaniu etnograficznym",
        "Struktura tekstu": "Refrenowa",
        "Uwagi": "Zachowanie lokalnych tradycji",
        "Obecność w źródłach": "Nagranie historyczne",
        "Tytuł": "Fletowe Pieśni z Wejherowa",
        "Artyści": [
            "Aleksandra Wiśniewska",
        ],
        "Rok": 2007,
    },
    {
        "Region": "Kaszuby",
        "Sygnatura nagrania": "KPL-333",
        "Incipit": "Incipit-33",
        "Numer wątku muzycznego": 37,
        "Numer w publikacji": 92,
        "Miejscowość": "Lębork",
        "Sposób wykonania": "Akordeon",
        "Funkcja utworu": "Obrzędowa",
        "Link do nagrania": "https://example.com/recording/333",
        "Źródło": "Dziedzictwo kulturowe",
        "Klasyfikacja melodyczna": "Skala molowa",
        "Kategoria": "Kaszubskie Pieśni Ludowe",
        "Wykorzystanie w publikacji": "W książce tematycznej",
        "Struktura tekstu": "Narracyjna",
        "Uwagi": "Autentyczne wykonanie",
        "Obecność w źródłach": "Rejestracja terenowa",
        "Tytuł": "Akordeonowe Melodie Lęborskie",
        "Artyści": [
            "Marek Nowak",
        ],
        "Rok": 2010,
    },
    {
        "Region": "Kaszuby",
        "Sygnatura nagrania": "KPL-222",
        "Incipit": "Incipit-32",
        "Numer wątku muzycznego": 35,
        "Numer w publikacji": 89,
        "Miejscowość": "Bytów",
        "Sposób wykonania": "Skrzypce",
        "Funkcja utworu": "Taneczna",
        "Link do nagrania": "https://example.com/recording/222",
        "Źródło": "Kolekcja prywatna",
        "Klasyfikacja melodyczna": "Skala dorycka",
        "Kategoria": "Kaszubskie Pieśni Ludowe",
        "Wykorzystanie w publikacji": "W monografii muzycznej",
        "Struktura tekstu": "Liryczna",
        "Uwagi": "Popularność wśród lokalnej społeczności",
        "Obecność w źródłach": "Nagranie współczesne",
        "Tytuł": "Skrzypcowe Dźwięki z Bytowa",
        "Artyści": [
            "Piotr Kowalski",
        ],
        "Rok": 2005,
    },
    {
        "Region": "Kaszuby",
        "Sygnatura nagrania": "KPL-111",
        "Incipit": "Incipit-31",
        "Numer wątku muzycznego": 33,
        "Numer w publikacji": 78,
        "Miejscowość": "Kościerzyna",
        "Sposób wykonania": "Harfa",
        "Funkcja utworu": "Uroczysta",
        "Link do nagrania": "https://example.com/recording/111",
        "Źródło": "Tradycja ludowa",
        "Klasyfikacja melodyczna": "Skala naturalna",
        "Kategoria": "Kaszubskie Pieśni Ludowe",
        "Wykorzystanie w publikacji": "W zbiorze regionalnym",
        "Struktura tekstu": "Balladowa",
        "Uwagi": "Zachowanie tradycji regionalnych",
        "Obecność w źródłach": "Nagranie archiwalne",
        "Tytuł": "Harfowe Brzmienia Kościerzyny",
        "Artyści": [
            "Anna Nowak",
        ],
        "Rok": 2001,
    },
    {
        "Region": "Tatry",
        "Sygnatura nagrania": "GNT-010",
        "Incipit": "Incipit-30",
        "Numer wątku muzycznego": 27,
        "Numer w publikacji": 68,
        "Miejscowość": "Czarna Góra",
        "Sposób wykonania": "Flet pasterski",
        "Funkcja utworu": "Pastoralna",
        "Link do nagrania": "https://example.com/recording/010",
        "Źródło": "Nagranie terenowe",
        "Klasyfikacja melodyczna": "Skala lydyjska",
        "Kategoria": "Góralskie Nuty z Tatr",
        "Wykorzystanie w publikacji": "W encyklopedii muzycznej",
        "Struktura tekstu": "Beztekstowa",
        "Uwagi": "Element pasterskiej tradycji",
        "Obecność w źródłach": "Archiwum regionalne",
        "Tytuł": "Fletowe Dźwięki z Czarnej Góry",
        "Artyści": [
            "Tomasz Baranowski",
        ],
        "Rok": 2012,
    },
    {
        "Region": "Tatry",
        "Sygnatura nagrania": "GNT-909",
        "Incipit": "Incipit-29",
        "Numer wątku muzycznego": 31,
        "Numer w publikacji": 96,
        "Miejscowość": "Witów",
        "Sposób wykonania": "Basy góralskie",
        "Funkcja utworu": "Folklorystyczna",
        "Link do nagrania": "https://example.com/recording/909",
        "Źródło": "Tradycja regionalna",
        "Klasyfikacja melodyczna": "Skala dorycka",
        "Kategoria": "Góralskie Nuty z Tatr",
        "Wykorzystanie w publikacji": "W książce tematycznej",
        "Struktura tekstu": "Narracyjna",
        "Uwagi": "Zachowanie lokalnego folkloru",
        "Obecność w źródłach": "Kolekcja prywatna",
        "Tytuł": "Basowe Dźwięki z Witowa",
        "Artyści": [
            "Aleksandra Wiśniewska",
        ],
        "Rok": 2019,
    },
    {
        "Region": "Tatry",
        "Sygnatura nagrania": "GNT-808",
        "Incipit": "Incipit-28",
        "Numer wątku muzycznego": 29,
        "Numer w publikacji": 82,
        "Miejscowość": "Chochołów",
        "Sposób wykonania": "Dudy góralskie",
        "Funkcja utworu": "Obrzędowa",
        "Link do nagrania": "https://example.com/recording/808",
        "Źródło": "Kolekcja ludowa",
        "Klasyfikacja melodyczna": "Skala pentatoniczna",
        "Kategoria": "Góralskie Nuty z Tatr",
        "Wykorzystanie w publikacji": "W opracowaniu regionalnym",
        "Struktura tekstu": "Powtarzalna",
        "Uwagi": "Autentyczność wykonania",
        "Obecność w źródłach": "Nagranie terenowe",
        "Tytuł": "Dudowe Echa Chochołowa",
        "Artyści": [
            "Piotr Szymański",
        ],
        "Rok": 2014,
    },
    {
        "Region": "Tatry",
        "Sygnatura nagrania": "GNT-707",
        "Incipit": "Incipit-27",
        "Numer wątku muzycznego": 25,
        "Numer w publikacji": 77,
        "Miejscowość": "Jurgów",
        "Sposób wykonania": "Mandolina",
        "Funkcja utworu": "Romantyczna",
        "Link do nagrania": "https://example.com/recording/707",
        "Źródło": "Zbiór prywatny",
        "Klasyfikacja melodyczna": "Skala mixolydzka",
        "Kategoria": "Góralskie Nuty z Tatr",
        "Wykorzystanie w publikacji": "W antologii muzycznej",
        "Struktura tekstu": "Liryczna",
        "Uwagi": "Fuzja nowoczesności z tradycją",
        "Obecność w źródłach": "Nagranie współczesne",
        "Tytuł": "Mandolinowe Melodie z Jurgowa",
        "Artyści": [
            "Anna Wiśniewska",
        ],
        "Rok": 2016,
    },
    {
        "Region": "Tatry",
        "Sygnatura nagrania": "GNT-606",
        "Incipit": "Incipit-26",
        "Numer wątku muzycznego": 23,
        "Numer w publikacji": 64,
        "Miejscowość": "Ząb",
        "Sposób wykonania": "Trombita",
        "Funkcja utworu": "Sygnałowa",
        "Link do nagrania": "https://example.com/recording/606",
        "Źródło": "Tradycja pasterska",
        "Klasyfikacja melodyczna": "Skala naturalna",
        "Kategoria": "Góralskie Nuty z Tatr",
        "Wykorzystanie w publikacji": "W dokumentacji etnograficznej",
        "Struktura tekstu": "Beztekstowa",
        "Uwagi": "Zachowanie tradycji pasterskich",
        "Obecność w źródłach": "Nagranie archiwalne",
        "Tytuł": "Dźwięki Trombity z Zębu",
        "Artyści": [
            "Michał Nowak",
        ],
        "Rok": 2008,
    },
    {
        "Region": "Tatry",
        "Sygnatura nagrania": "GNT-505",
        "Incipit": "Incipit-25",
        "Numer wątku muzycznego": 18,
        "Numer w publikacji": 61,
        "Miejscowość": "Murzasichle",
        "Sposób wykonania": "Basy i fujarka",
        "Funkcja utworu": "Imprezowa",
        "Link do nagrania": "https://example.com/recording/505",
        "Źródło": "Kolekcja prywatna",
        "Klasyfikacja melodyczna": "Skala mixolydzka",
        "Kategoria": "Góralskie Nuty z Tatr",
        "Wykorzystanie w publikacji": "W opracowaniu folklorystycznym",
        "Struktura tekstu": "Humorystyczna",
        "Uwagi": "Energiczne rytmiki",
        "Obecność w źródłach": "Nagranie współczesne",
        "Tytuł": "Wesołe nuty z Murzasichla",
        "Artyści": [
            "Tomasz Baranowski",
        ],
        "Rok": 2015,
    },
    {
        "Region": "Tatry",
        "Sygnatura nagrania": "GNT-404",
        "Incipit": "Incipit-24",
        "Numer wątku muzycznego": 11,
        "Numer w publikacji": 29,
        "Miejscowość": "Poronin",
        "Sposób wykonania": "Fujarka",
        "Funkcja utworu": "Liryczna",
        "Link do nagrania": "https://example.com/recording/404",
        "Źródło": "Rejestracja terenowa",
        "Klasyfikacja melodyczna": "Skala diatoniczna",
        "Kategoria": "Góralskie Nuty z Tatr",
        "Wykorzystanie w publikacji": "W encyklopedii regionalnej",
        "Struktura tekstu": "Kupletowa",
        "Uwagi": "Unikalne wykonanie",
        "Obecność w źródłach": "Nagranie festiwalowe",
        "Tytuł": "Fujarkowe Melodie Poronińskie",
        "Artyści": [
            "Aleksandra Wiśniewska",
        ],
        "Rok": 2011,
    },
    {
        "Region": "Tatry",
        "Sygnatura nagrania": "GNT-303",
        "Incipit": "Incipit-23",
        "Numer wątku muzycznego": 16,
        "Numer w publikacji": 55,
        "Miejscowość": "Bukowina Tatrzańska",
        "Sposób wykonania": "Harmonia góralska",
        "Funkcja utworu": "Świąteczna",
        "Link do nagrania": "https://example.com/recording/303",
        "Źródło": "Dziedzictwo kulturowe",
        "Klasyfikacja melodyczna": "Skala pentatoniczna",
        "Kategoria": "Góralskie Nuty z Tatr",
        "Wykorzystanie w publikacji": "W albumie muzycznym",
        "Struktura tekstu": "Powtarzalna",
        "Uwagi": "Charakterystyczne brzmienie",
        "Obecność w źródłach": "Nagranie dokumentacyjne",
        "Tytuł": "Harmonie Bukowiańskie",
        "Artyści": [
            "Piotr Szymański",
        ],
        "Rok": 2007,
    },
    {
        "Region": "Tatry",
        "Sygnatura nagrania": "GNT-202",
        "Incipit": "Incipit-22",
        "Numer wątku muzycznego": 21,
        "Numer w publikacji": 47,
        "Miejscowość": "Kościelisko",
        "Sposób wykonania": "Cymbały",
        "Funkcja utworu": "Obrzędowa",
        "Link do nagrania": "https://example.com/recording/202",
        "Źródło": "Kolekcja regionalna",
        "Klasyfikacja melodyczna": "Skala molowa",
        "Kategoria": "Góralskie Nuty z Tatr",
        "Wykorzystanie w publikacji": "W zbiorze pieśni",
        "Struktura tekstu": "Narracyjna",
        "Uwagi": "Tradycyjne wykonanie",
        "Obecność w źródłach": "Archiwum ludowe",
        "Tytuł": "Cymbałowe dźwięki z Kościeliska",
        "Artyści": [
            "Maria Nowak",
        ],
        "Rok": 2003,
    },
    {
        "Region": "Tatry",
        "Sygnatura nagrania": "GNT-101",
        "Incipit": "Incipit-21",
        "Numer wątku muzycznego": 17,
        "Numer w publikacji": 38,
        "Miejscowość": "Zakopane",
        "Sposób wykonania": "Skrypka i basy",
        "Funkcja utworu": "Taneczna",
        "Link do nagrania": "https://example.com/recording/101",
        "Źródło": "Tradycja góralska",
        "Klasyfikacja melodyczna": "Skala durowa",
        "Kategoria": "Góralskie Nuty z Tatr",
        "Wykorzystanie w publikacji": "W opracowaniu etnograficznym",
        "Struktura tekstu": "Liryczna",
        "Uwagi": "Zachowanie autentyczności",
        "Obecność w źródłach": "Nagranie terenowe",
        "Tytuł": "Melodie Zakopiańskie",
        "Artyści": [
            "Jan Kowalski",
        ],
        "Rok": 1999,
    },
    {
        "Region": "Warmia i Mazury",
        "Sygnatura nagrania": "TMW-000",
        "Incipit": "Incipit-20",
        "Numer wątku muzycznego": 8,
        "Numer w publikacji": 44,
        "Miejscowość": "Szczytno",
        "Sposób wykonania": "Harmonia",
        "Funkcja utworu": "Uroczysta",
        "Link do nagrania": "https://example.com/recording/000",
        "Źródło": "Rejestracja muzealna",
        "Klasyfikacja melodyczna": "Skala heksatoniczna",
        "Kategoria": "Tradycyjne Pieśni Warmii i Mazur",
        "Wykorzystanie w publikacji": "W dokumentacji muzycznej",
        "Struktura tekstu": "Balladowa",
        "Uwagi": "Ożywienie kultury ludowej",
        "Obecność w źródłach": "Nagranie festiwalowe",
        "Tytuł": "Harmonie Szczytna",
        "Artyści": [
            "Ewa Kowalska",
        ],
        "Rok": 2018,
    },
    {
        "Region": "Warmia i Mazury",
        "Sygnatura nagrania": "TMW-999",
        "Incipit": "Incipit-19",
        "Numer wątku muzycznego": 10,
        "Numer w publikacji": 60,
        "Miejscowość": "Ostróda",
        "Sposób wykonania": "Klarnet",
        "Funkcja utworu": "Świąteczna",
        "Link do nagrania": "https://example.com/recording/999",
        "Źródło": "Zbiór etnograficzny",
        "Klasyfikacja melodyczna": "Skala lidyjska",
        "Kategoria": "Tradycyjne Pieśni Warmii i Mazur",
        "Wykorzystanie w publikacji": "W zbiorze pieśni regionalnych",
        "Struktura tekstu": "Refrenowa",
        "Uwagi": "Popularność wśród starszego pokolenia",
        "Obecność w źródłach": "Nagranie archiwalne",
        "Tytuł": "Klarnetowe dźwięki Ostródy",
        "Artyści": [
            "Piotr Szymański",
        ],
        "Rok": 2010,
    },
    {
        "Region": "Warmia i Mazury",
        "Sygnatura nagrania": "TMW-888",
        "Incipit": "Incipit-18",
        "Numer wątku muzycznego": 1,
        "Numer w publikacji": 20,
        "Miejscowość": "Lidzbark Warmiński",
        "Sposób wykonania": "Fujarka",
        "Funkcja utworu": "Pastoralna",
        "Link do nagrania": "https://example.com/recording/888",
        "Źródło": "Archiwum lokalne",
        "Klasyfikacja melodyczna": "Skala frygijska",
        "Kategoria": "Tradycyjne Pieśni Warmii i Mazur",
        "Wykorzystanie w publikacji": "W książce etnograficznej",
        "Struktura tekstu": "Narracyjno-liryczna",
        "Uwagi": "Zachowanie tradycyjnych melodii",
        "Obecność w źródłach": "Nagranie terenowe",
        "Tytuł": "Pieśni Lidzbarka Warmińskiego",
        "Artyści": [
            "Aleksandra Wiśniewska",
        ],
        "Rok": 2014,
    },
    {
        "Region": "Warmia i Mazury",
        "Sygnatura nagrania": "TMW-777",
        "Incipit": "Incipit-17",
        "Numer wątku muzycznego": 6,
        "Numer w publikacji": 32,
        "Miejscowość": "Kętrzyn",
        "Sposób wykonania": "Lira korbowa",
        "Funkcja utworu": "Historyczna",
        "Link do nagrania": "https://example.com/recording/777",
        "Źródło": "Kolekcja prywatna",
        "Klasyfikacja melodyczna": "Skala dorycka",
        "Kategoria": "Tradycyjne Pieśni Warmii i Mazur",
        "Wykorzystanie w publikacji": "W albumie muzyki ludowej",
        "Struktura tekstu": "Epicka",
        "Uwagi": "Unikatowe dziedzictwo muzyczne",
        "Obecność w źródłach": "Rejestracja muzealna",
        "Tytuł": "Dźwięki Kętrzyna",
        "Artyści": [
            "Michał Nowak",
        ],
        "Rok": 2017,
    },
    {
        "Region": "Warmia i Mazury",
        "Sygnatura nagrania": "TMW-666",
        "Incipit": "Incipit-16",
        "Numer wątku muzycznego": 13,
        "Numer w publikacji": 49,
        "Miejscowość": "Braniewo",
        "Sposób wykonania": "Bęben",
        "Funkcja utworu": "Rytualna",
        "Link do nagrania": "https://example.com/recording/666",
        "Źródło": "Tradycja ustna",
        "Klasyfikacja melodyczna": "Skala naturalna",
        "Kategoria": "Tradycyjne Pieśni Warmii i Mazur",
        "Wykorzystanie w publikacji": "W opracowaniu regionalnym",
        "Struktura tekstu": "Onomatopeiczna",
        "Uwagi": "Zachowanie dawnych tradycji",
        "Obecność w źródłach": "Nagranie archiwalne",
        "Tytuł": "Rytmy Braniewa",
        "Artyści": [
            "Katarzyna Jankowska",
        ],
        "Rok": 2009,
    },
    {
        "Region": "Warmia i Mazury",
        "Sygnatura nagrania": "TMW-555",
        "Incipit": "Incipit-15",
        "Numer wątku muzycznego": 4,
        "Numer w publikacji": 75,
        "Miejscowość": "Iława",
        "Sposób wykonania": "Gitara",
        "Funkcja utworu": "Imprezowa",
        "Link do nagrania": "https://example.com/recording/555",
        "Źródło": "Kolekcja lokalna",
        "Klasyfikacja melodyczna": "Skala mixolydzka",
        "Kategoria": "Tradycyjne Pieśni Warmii i Mazur",
        "Wykorzystanie w publikacji": "W zbiorze regionalnym",
        "Struktura tekstu": "Kupletowa",
        "Uwagi": "Odrodzenie kultury ludowej",
        "Obecność w źródłach": "Nagranie z festiwalu",
        "Tytuł": "Gitary Iławy",
        "Artyści": [
            "Tomasz Baranowski",
        ],
        "Rok": 2013,
    },
    {
        "Region": "Warmia i Mazury",
        "Sygnatura nagrania": "TMW-444",
        "Incipit": "Incipit-14",
        "Numer wątku muzycznego": 22,
        "Numer w publikacji": 63,
        "Miejscowość": "Mrągowo",
        "Sposób wykonania": "Flet",
        "Funkcja utworu": "Liryczna",
        "Link do nagrania": "https://example.com/recording/444",
        "Źródło": "Zbiór etnograficzny",
        "Klasyfikacja melodyczna": "Skala pentatoniczna",
        "Kategoria": "Tradycyjne Pieśni Warmii i Mazur",
        "Wykorzystanie w publikacji": "W dokumentacji folklorystycznej",
        "Struktura tekstu": "Refrenowa",
        "Uwagi": "Zachowanie tradycji muzycznych regionu",
        "Obecność w źródłach": "Nagranie historyczne",
        "Tytuł": "Flauta Mrągowska",
        "Artyści": [
            "Piotr Szymański",
        ],
        "Rok": 2008,
    },
    {
        "Region": "Warmia i Mazury",
        "Sygnatura nagrania": "TMW-333",
        "Incipit": "Incipit-13",
        "Numer wątku muzycznego": 19,
        "Numer w publikacji": 42,
        "Miejscowość": "Giżycko",
        "Sposób wykonania": "Harmonijka ustna",
        "Funkcja utworu": "Towarzyska",
        "Link do nagrania": "https://example.com/recording/333",
        "Źródło": "Nagranie domowe",
        "Klasyfikacja melodyczna": "Skala bluesowa",
        "Kategoria": "Tradycyjne Pieśni Warmii i Mazur",
        "Wykorzystanie w publikacji": "W antologii regionalnej",
        "Struktura tekstu": "Liryczna",
        "Uwagi": "Popularne wśród lokalnej społeczności",
        "Obecność w źródłach": "Rejestracja współczesna",
        "Tytuł": "Dźwięki Giżycka",
        "Artyści": [
            "Anna Wiśniewska",
        ],
        "Rok": 2012,
    },
    {
        "Region": "Warmia i Mazury",
        "Sygnatura nagrania": "TMW-222",
        "Incipit": "Incipit-12",
        "Numer wątku muzycznego": 14,
        "Numer w publikacji": 56,
        "Miejscowość": "Ełk",
        "Sposób wykonania": "Skrzypce",
        "Funkcja utworu": "Obrzędowa",
        "Link do nagrania": "https://example.com/recording/222",
        "Źródło": "Kolekcja prywatna",
        "Klasyfikacja melodyczna": "Skala molowa",
        "Kategoria": "Tradycyjne Pieśni Warmii i Mazur",
        "Wykorzystanie w publikacji": "W opracowaniu etnomuzykologicznym",
        "Struktura tekstu": "Balladowa",
        "Uwagi": "Element regionalnego dziedzictwa",
        "Obecność w źródłach": "Nagranie terenowe",
        "Tytuł": "Pieśni Ełckie",
        "Artyści": [
            "Marek Nowak",
        ],
        "Rok": 2006,
    },
    {
        "Region": "Warmia i Mazury",
        "Sygnatura nagrania": "TMW-111",
        "Incipit": "Incipit-11",
        "Numer wątku muzycznego": 7,
        "Numer w publikacji": 30,
        "Miejscowość": "Olsztyn",
        "Sposób wykonania": "Wokal i akordeon",
        "Funkcja utworu": "Uroczysta",
        "Link do nagrania": "https://example.com/recording/111",
        "Źródło": "Tradycja ludowa",
        "Klasyfikacja melodyczna": "Skala durowa",
        "Kategoria": "Tradycyjne Pieśni Warmii i Mazur",
        "Wykorzystanie w publikacji": "W zbiorze pieśni ludowych",
        "Struktura tekstu": "Narracyjna",
        "Uwagi": "Stylizacja ludowa",
        "Obecność w źródłach": "Nagranie archiwalne",
        "Tytuł": "Melodie Olsztyńskie",
        "Artyści": [
            "Zofia Kowalska",
        ],
        "Rok": 2004,
    },
    {
        "Region": "Wielkopolska",
        "Sygnatura nagrania": "WLM-010",
        "Incipit": "Incipit-10",
        "Numer wątku muzycznego": 5,
        "Numer w publikacji": 94,
        "Miejscowość": "Wągrowiec",
        "Sposób wykonania": "Bębny",
        "Funkcja utworu": "Rytualna",
        "Link do nagrania": "https://example.com/recording/010",
        "Źródło": "Rejestracja terenowa",
        "Klasyfikacja melodyczna": "Skala frygijska",
        "Kategoria": "Wielkopolska",
        "Wykorzystanie w publikacji": "W encyklopedii regionalnej",
        "Struktura tekstu": "Onomatopeiczna",
        "Uwagi": "Tradycyjne rytmy",
        "Obecność w źródłach": "Archiwum ludowe",
        "Tytuł": "Bębny Wągrowca",
        "Artyści": [
            "Paweł Nowicki",
        ],
        "Rok": 2018,
    },
    {
        "Region": "Wielkopolska",
        "Sygnatura nagrania": "WLM-909",
        "Incipit": "Incipit-9",
        "Numer wątku muzycznego": 2,
        "Numer w publikacji": 53,
        "Miejscowość": "Rawicz",
        "Sposób wykonania": "Saksofon",
        "Funkcja utworu": "Imprezowa",
        "Link do nagrania": "https://example.com/recording/909",
        "Źródło": "Dziedzictwo lokalne",
        "Klasyfikacja melodyczna": "Skala lidyjska",
        "Kategoria": "Wielkopolska",
        "Wykorzystanie w publikacji": "W opracowaniu naukowym",
        "Struktura tekstu": "Humorystyczna",
        "Uwagi": "Element kultury miejskiej",
        "Obecność w źródłach": "Nagranie dokumentalne",
        "Tytuł": "Swingi Rawicza",
        "Artyści": [
            "Ewa Szymańska",
        ],
        "Rok": 2003,
    },
    {
        "Region": "Wielkopolska",
        "Sygnatura nagrania": "WLM-808",
        "Incipit": "Incipit-8",
        "Numer wątku muzycznego": 9,
        "Numer w publikacji": 39,
        "Miejscowość": "Gostyń",
        "Sposób wykonania": "Klarnet",
        "Funkcja utworu": "Towarzyska",
        "Link do nagrania": "https://example.com/recording/808",
        "Źródło": "Zbiór uniwersytecki",
        "Klasyfikacja melodyczna": "Skala dorycka",
        "Kategoria": "Wielkopolska",
        "Wykorzystanie w publikacji": "W podręczniku muzyki",
        "Struktura tekstu": "Kupletowa",
        "Uwagi": "Popularność wśród młodzieży",
        "Obecność w źródłach": "Nagranie edukacyjne",
        "Tytuł": "Rytmy Gostynia",
        "Artyści": [
            "Marek Kowalczyk",
        ],
        "Rok": 2015,
    },
    {
        "Region": "Wielkopolska",
        "Sygnatura nagrania": "WLM-707",
        "Incipit": "Incipit-7",
        "Numer wątku muzycznego": 11,
        "Numer w publikacji": 88,
        "Miejscowość": "Piła",
        "Sposób wykonania": "Banjo",
        "Funkcja utworu": "Folklorystyczna",
        "Link do nagrania": "https://example.com/recording/707",
        "Źródło": "Zbiór etnograficzny",
        "Klasyfikacja melodyczna": "Skala mixolydzka",
        "Kategoria": "Wielkopolska",
        "Wykorzystanie w publikacji": "W zbiorze pieśni",
        "Struktura tekstu": "Balladowa",
        "Uwagi": "Charakterystyczne dla regionu",
        "Obecność w źródłach": "Kolekcja muzealna",
        "Tytuł": "Melodie z Piły",
        "Artyści": [
            "Agnieszka Nowak",
        ],
        "Rok": 2007,
    },
    {
        "Region": "Wielkopolska",
        "Sygnatura nagrania": "WLM-606",
        "Incipit": "Incipit-6",
        "Numer wątku muzycznego": 3,
        "Numer w publikacji": 72,
        "Miejscowość": "Ostrów Wielkopolski",
        "Sposób wykonania": "Gitara",
        "Funkcja utworu": "Opowieściowa",
        "Link do nagrania": "https://example.com/recording/606",
        "Źródło": "Tradycja oralna",
        "Klasyfikacja melodyczna": "Skala bluesowa",
        "Kategoria": "Wielkopolska",
        "Wykorzystanie w publikacji": "W monografii regionalnej",
        "Struktura tekstu": "Epicka",
        "Uwagi": "Unikalny styl wykonania",
        "Obecność w źródłach": "Rejestracja terenowa",
        "Tytuł": "Bluesy Ostrowa",
        "Artyści": [
            "Krzysztof Jankowski",
        ],
        "Rok": 2011,
    },
    {
        "Region": "Wielkopolska",
        "Sygnatura nagrania": "WLM-505",
        "Incipit": "Incipit-5",
        "Numer wątku muzycznego": 4,
        "Numer w publikacji": 51,
        "Miejscowość": "Konin",
        "Sposób wykonania": "Bas",
        "Funkcja utworu": "Liryczna",
        "Link do nagrania": "https://example.com/recording/505",
        "Źródło": "Zbiór ludowy",
        "Klasyfikacja melodyczna": "Skala diatoniczna",
        "Kategoria": "Wielkopolska",
        "Wykorzystanie w publikacji": "W antologii",
        "Struktura tekstu": "Liryczna",
        "Uwagi": "Element folkloru",
        "Obecność w źródłach": "Kolekcja prywatna",
        "Tytuł": "Ballady Konina",
        "Artyści": [
            "Tomasz Baranowski",
        ],
        "Rok": 2001,
    },
    {
        "Region": "Wielkopolska",
        "Sygnatura nagrania": "WLM-404",
        "Incipit": "Incipit-4",
        "Numer wątku muzycznego": 10,
        "Numer w publikacji": 36,
        "Miejscowość": "Leszno",
        "Sposób wykonania": "Harmonia",
        "Funkcja utworu": "Świąteczna",
        "Link do nagrania": "https://example.com/recording/404",
        "Źródło": "Dziedzictwo regionalne",
        "Klasyfikacja melodyczna": "Modalna",
        "Kategoria": "Wielkopolska",
        "Wykorzystanie w publikacji": "W książce tematycznej",
        "Struktura tekstu": "Powtarzalna",
        "Uwagi": "Znane lokalnie",
        "Obecność w źródłach": "Nagranie współczesne",
        "Tytuł": "Harmonie Leszna",
        "Artyści": [
            "Aleksandra Wiśniewska",
        ],
        "Rok": 2016,
    },
    {
        "Region": "Wielkopolska",
        "Sygnatura nagrania": "WLM-303",
        "Incipit": "Incipit-3",
        "Numer wątku muzycznego": 15,
        "Numer w publikacji": 22,
        "Miejscowość": "Gniezno",
        "Sposób wykonania": "Flet",
        "Funkcja utworu": "Religijna",
        "Link do nagrania": "https://example.com/recording/303",
        "Źródło": "Zbiór kościelny",
        "Klasyfikacja melodyczna": "Skala heksatoniczna",
        "Kategoria": "Wielkopolska",
        "Wykorzystanie w publikacji": "Dokumentacja etnograficzna",
        "Struktura tekstu": "Beztekstowe",
        "Uwagi": "Zachowana tradycja",
        "Obecność w źródłach": "Nagranie historyczne",
        "Tytuł": "Dźwięki Gniezna",
        "Artyści": [
            "Piotr Szymański",
        ],
        "Rok": 2010,
    },
    {
        "Region": "Wielkopolska",
        "Region etnograficzny": "Szamotulskie",
        "Sygnatura nagrania": "WLM-303",
        "Incipit": "Incipit-3",
        "Numer wątku muzycznego": 15,
        "Numer w publikacji": 22,
        "Miejscowość": "Gniezno",
        "Sposób wykonania": "Flet",
        "Funkcja utworu": "Religijna",
        "Link do nagrania": "https://example.com/recording/303",
        "Źródło": "Zbiór kościelny",
        "Klasyfikacja melodyczna": "Skala heksatoniczna",
        "Kategoria": "Wielkopolska",
        "Wykorzystanie w publikacji": "Dokumentacja etnograficzna",
        "Struktura tekstu": "Beztekstowe",
        "Uwagi": "Zachowana tradycja",
        "Obecność w źródłach": "Nagranie historyczne",
        "Tytuł": "Dźwięki Gniezna",
        "Artyści": [
            "Piotr Szymański",
        ],
        "Rok": 2010,
    },
    {
        "Region": "Wielkopolska",
        "Sygnatura nagrania": "WLM-202",
        "Incipit": "Incipit-2",
        "Numer wątku muzycznego": 8,
        "Numer w publikacji": 67,
        "Miejscowość": "Kalisz",
        "Sposób wykonania": "Skrypka",
        "Funkcja utworu": "Obrzędowa",
        "Link do nagrania": "https://example.com/recording/202",
        "Źródło": "Zbiór prywatny",
        "Klasyfikacja melodyczna": "Skala molowa",
        "Kategoria": "Wielkopolska",
        "Wykorzystanie w publikacji": "Rzadko dokumentowany",
        "Struktura tekstu": "Narracyjna",
        "Uwagi": "Unikatowe wykonanie",
        "Obecność w źródłach": "Nagranie terenowe",
        "Tytuł": "Melodie Kalisza",
        "Artyści": [
            "Maria Nowak",
        ],
        "Rok": 2005,
    },
    {
        "Region": "Wielkopolska",
        "Sygnatura nagrania": "WLM-101",
        "Incipit": "Incipit-1",
        "Numer wątku muzycznego": 12,
        "Numer w publikacji": 45,
        "Miejscowość": "Poznań",
        "Sposób wykonania": "Akordeon",
        "Funkcja utworu": "Taneczna",
        "Link do nagrania": "https://example.com/recording/101",
        "Źródło": "Zbiór ludowy",
        "Klasyfikacja melodyczna": "Skala dur",
        "Kategoria": "Wielkopolska",
        "Wykorzystanie w publikacji": "Często dokumentowany",
        "Struktura tekstu": "Refrenowa",
        "Uwagi": "Popularny w regionie",
        "Obecność w źródłach": "Nagranie archiwalne",
        "Tytuł": "Rytmy Wielkopolski",
        "Artyści": [
            "Jan Kowalski",
        ],
        "Rok": 1998,
    },
]

const collectionData = [
    {
        "name": "Kaszubskie Pieśni Ludowe",
        "description": "Pieśni z regionu Kaszub, podkreślające unikalny język i dziedzictwo kulturowe Kaszubów.",
    },
    {
        "name": "Góralskie Nuty z Tatr",
        "description": "Antologia muzyki z Tatr, prezentująca charakterystyczny styl polskich górali.",
    },
    {
        "name": "Śląska Kolekcja Muzyki Ludowej",
        "description": "Kompilacja muzyki ludowej ze Śląska, ilustrująca bogatą historię przemysłową i kulturalną regionu.",
    },
    {
        "name": "Wielkopolska",
        "description": "Zbiór muzyki ludowej z regionu Wielkopolski, ukazujący bogactwo tradycji muzycznych tego obszaru, w tym tradycyjne instrumenty i unikalne style.",
    },
    {
        "name": "Tradycyjne Pieśni Warmii i Mazur",
        "description": "Kolekcja ludowych pieśni z regionów Warmii i Mazur, odzwierciedlająca unikalne połączenie kultu rowe tych obszarów.",
    },
]

const categoryData = [
    {
        "category": "Region",
        "label": "Wielkopolska",
        "locationDetails": [
            {
                "label": "Podregion",
                "values": [
                    "Wielkopolska Północno-Zachodnia",
                    "Wielkopolska Północno-Wschodnia",
                    "Wielkopolska Południowo-Zachodnia",
                    "Wielkopolska Południowo-Wschodnia",
                ],
                "isSelectable": true,
            },
            {
                "label": "Region etnograficzny",
                "values": [
                    "Szamotulskie",
                    "Ziemia Lubuska",
                    "Kaliskie"
                ],
                "isSelectable": true,
            },
            {
                "label": "Powiat",
                "values": [
                    "Gniezno",
                    "Poznań",
                    "Września",
                    "Środa"
                ],
                "isSelectable": true,
            },
            {
                "label": "Miejscowość",
                "values": [
                    "Leszno",
                    "Kalisz",
                    "Konin",
                    "Piła",
                    "Ostrów Wielkopolski",
                ],
                "isSelectable": true,
            },
            {
                "label": "Sygnatura nagrania",
                "subcategories": [
                    {
                        "label": "Pozycja",
                        "values": [],
                    },
                ],
                "isSelectable": false,
            },
            {
                "label": "Incipit",
                "subcategories": [
                    {
                        "label": "Język incipitu",
                        "values": ["angielski", "niemiecki"],
                    },
                ],
                "isSelectable": true,
            },
            {
                "label": "Nazwisko wykonawcy",
                "subcategories": [
                    {
                        "label": "Wykonawca",
                        "values": ["sadjkasdkjsda", "sadjkasdkjsda", "sadjkasdkjsda"],
                    },
                ],
                "isSelectable": false,
            },
            {
                "label": "Numer wątku muzycznego",
                "subcategories": [],
                "isSelectable": false,
            },
            {
                "label": "Numer w publikacji",
                "subcategories": [],
                "isSelectable": false,
            },
            {
                "label": "Sposób wykonania",
                "subcategories": [
                    { "label": "Barwa głosu", "values": [], "isSelectable": false },
                    { "label": "Tempo wykonania", "values": [], "isSelectable": false },
                    { "label": "Ornamentyka", "values": [], "isSelectable": false },
                ],
                "isSelectable": true,
            },
            {
                "label": "Funkcja utworu ogólnie",
                "subcategories": [
                    { "label": "Szczegółowa funkcja", "values": [], "isSelectable": false },
                    { "label": "Funkcja określona przez wykonawcę", "values": [], "isSelectable": false },
                ],
                "isSelectable": true,
            },
            {
                "label": "Numer wątku melodycznego",
                "subcategories": [],
                "isSelectable": false,
            },
            {
                "label": "Wykorzystanie w publikacji",
                "subcategories": [],
                "isSelectable": false,
            },
            {
                "label": "Klasyfikacja melodyczna",
                "subcategories": [
                    { "label": "Rytmika", "values": [], "isSelectable": false },
                    { "label": "Metrum", "values": [], "isSelectable": false },
                    { "label": "Forma melodyczna", "values": [], "isSelectable": false },
                    { "label": "Skala", "values": [], "isSelectable": false },
                    { "label": "Ambitus", "values": [], "isSelectable": false },
                    { "label": "Układ kadencji", "values": [], "isSelectable": false },
                ],
                "isSelectable": true,
            },
            {
                "label": "Struktura tekstu",
                "subcategories": [
                    { "label": "Ilość wersów", "values": [], "isSelectable": false },
                    { "label": "Układ sylab w wersie", "values": [], "isSelectable": false },
                ],
                "isSelectable": true,
            },
            {
                "label": "Uwagi",
                "subcategories": [
                    { "label": "Stan techniczny nagrania", "values": [], "isSelectable": false },
                    { "label": "Walory melodii", "values": [], "isSelectable": false },
                ],
                "isSelectable": false,
            },
            {
                "label": "Obecność w źródłach",
                "subcategories": [
                    { "label": "Antologie", "values": [], "isSelectable": false },
                    { "label": "Rękopisy", "values": [], "isSelectable": false },
                    { "label": "Śpiewniki", "values": [], "isSelectable": false },
                ],
                "isSelectable": true,
            },
        ],
    },
]


const userData = [
    {
        "username": "test",
        "firstName": "Zuzanna",
        "password": "$2b$10$KsgIW2Vj/bVci/T91q0Pr.ldzX5HPX/F4kf.wIMqgsJU4nDHiQigm",
    },
]

const isDatabaseEmpty = async () => {
    const userExists = await User.findOne().exec()
    const artworkExists = await Artwork.findOne().exec()
    const collectionExists = await Collection.findOne().exec()
    const categoryExists = await Category.findOne().exec()

    return !userExists && !artworkExists && !collectionExists && !categoryExists
}

const Collection = require("./models/collection")
const Category = require("./models/category")
const Artwork = require("./models/artwork")
const User = require("./models/user")


const initializeDatabase = async () => {
    await mongoose.connection.dropDatabase()
    const empty = await isDatabaseEmpty()

    if (empty) {
        const insertedUsers = await User.insertMany(userData)

        const userId = insertedUsers[0]._id
        const collectionsWithUser = collectionData.map(collection => ({
            ...collection,
            userId: userId,
        }))

        const insertedCollections = await Collection.insertMany(collectionsWithUser)

        // const artworksDataGreaterPoland = insertedCollections.reduce((map: any, collection: any) => {
        //     map[collection.name] = collection._id
        //     return map
        // }, {})

        const updatedArtworks = artworksData.map(artwork => ({
            ...artwork,
            collectionName: artwork.Region === "Wielkopolska" ? "Wielkopolska" : undefined,
            userId: userId,
        }));

        await Artwork.insertMany(updatedArtworks)

        const categoriesMap = categoryData.map(category => {
            return {
                ...category,
                collectionName: "Wielkopolska"
            }
        })

        await Category.insertMany(categoriesMap)


        console.log("Artworks collection initialized")
    }
}

export default initializeDatabase